### ISSUE TITLE
Modification des paramètres proxy à la validation

### ISSUE THREAD

**Issue by qvandekadsye** [Deuchnord/currentmood#1]
Salut, il faudra trouver un moyen de modifier les paramètres proxy quand on clique sur OK

**Comment by Deuchnord** [comment]
Hello,
Il y a une méthode [`setProxy()` dans `CMTwitter`](https://github.com/Deuchnord/currentmood/blob/master/src/currentmood/util/CMTwitter.java#L37) qui permet de paramétrer les paramètres proxy. Cette méthode doit être appelée _avant_ `connect()` pour fonctionner (j'ajouterai de la Javadoc pour le préciser).
Comme la connexion à Twitter est fermée dès que l'on récupère les tweets, il suffira de d'appeler `setproxy()` après la première tentative de connexion.
