### ISSUE TITLE
CSVFile: escape the new lines in the tweets

### ISSUE THREAD

**Issue by Deuchnord** [Deuchnord/currentmood#4]
Tweets may contain several lines, we need to escape the new lines before saving them in CSV format.

Also, we should check if there aren't some things in tweets that could be removed.

**Comment by Deuchnord** [comment]
Bug fixed in 6810f456b3d9f9bf285234b8c33118e7e5861fcc.

**Comment by qvandekadsye** [comment]
Another parsing bug with the file tweetv5.csv
You need to make a regex for ","
