### ISSUE TITLE
Mettre à jour l'annotation d'un tweet

### ISSUE THREAD

**Issue by Deuchnord** [Deuchnord/currentmood#6]
Il faut mettre à jour l'affichage de l'annotation d'un tweet lorsqu'on la met à jour.

**Comment by qvandekadsye** [comment]
C'est fait, mais je ne ferme pas de suite

**Comment by Deuchnord** [comment]
> Only you
> Can make all this world seem right
> Only you
> Can make the darkness bright
> Only you and you alone
> Can thrill me like you do
> And fill my heart with love for only you
> 
> O-only you
> Can make all this change in me
> For it's true
> You are my destiny
> When you hold my hand, I understand
> The magic that you do
> You're my dream come true
> My one and only you
> 
> O-o-only you
> Can make all this change in me
> For it's true
> 
> You are my destiny
> When you hold my hand,
> I understand
> The magic that you do
> You're my dream come true
> My one and only you
> (One and only you)
