### ISSUE TITLE
Remarque par rapport à la base de données

### ISSUE THREAD

**Issue by qvandekadsye** [Deuchnord/currentmood#7]
Cherchant la raison pour laquelle bayes, annotait tous les Tweet en "bon". Je me suis mis à lancer KNN avec les mots-clé "morts" et "chagrin". avec K=7, 300 et 700.
Les résultats sont les suivants, A peu près 3/4 sont "Bon" 20% Mauvais et 10 neutre

Du coup, je me suis mis à afficher le graphique de la base chaque fois qu'on la charge:
1)Notre base d'un millier de tweet est très mal proportionnées : 83% de bon, 10% de neutre 7% de mauvais.

2)La base tweetV6 est un peu plus équilibrée : 41,39,20

Il faudrait donc équilibrer la base.

Autre chose : est-il nécessaire d'ajouter à la base de tweet, les tweets qui ne sont pas annotés à la main ?

**Comment by Deuchnord** [comment]
Pour l'équilibrage, on en a parlé ce matin, je vais voir pour écrire un petit script qui fasse ça automatiquement pour pas perdre trop de temps.

> Autre chose : est-il nécessaire d'ajouter à la base de tweet, les tweets qui ne sont pas annotés à la main ?

Je ne suis pas pour : si des erreurs se glissent dans les annotations automatiques, cela faussera les estimations ultérieures, non ?
